# UUID Finder by LeonTG77 config.

UUIDFinder:
    # The prefix for the command messages.
    Prefix: '&8[&aUUIDFinder&8] &f'
    # The no permission message.
    NoPermissionMsg: '&cYou do not have access to that command.'
